### PR TITLE
Fix compiler warning and init() behaviour

### LINKED ISSUE #16: [remove Compiler Warning]: caused by unused Variable in SHTSensor.h
Hi,

I have  a proposal to remove a silly Compiler warning in line 160 of SHTSensor.h:

> see here:
``` 
          virtual bool setAccuracy(SHTSensor::SHTAccuracy newAccuracy) {
                 return false;
          }
```

> causes a silly compiler warning which can be prevented like:
```
          virtual bool setAccuracy(SHTSensor::SHTAccuracy newAccuracy) {
                (void) newAccuracy;
                return false;
          }
```

### PR DESCRIPTION
**Pull request by winkj**
Two bugfixes reported in ticket #16:
- unused variable marked as such to avoid compiler warning
- init() was updated to behave the same way whether the user called with in auto-detect mode, or with a fixed sensor type: previously, only the auto-detect case would also attempt to read from the sensor, now both code paths will do so

### CODE REVIEW

File: SHTSensor.h [hunk 1]
```diff
@@ -157,7 +166,7 @@ class SHTSensorDriver
    * Set the sensor accuracy.
    * Returns false if the sensor does not support changing the accuracy
    */
-  virtual bool setAccuracy(SHTSensor::SHTAccuracy newAccuracy) {
+  virtual bool setAccuracy(__attribute__((unused)) SHTSensor::SHTAccuracy newAccuracy) {
```
Comment (rnestler) [inline SHTSensor.h]: I'm not sure how portable `__attribute__((unused))` is and if it works with all Arduino compilers.

Comment (winkj) [reply SHTSensor.h]: I figured Arduino is mainly g++, but valid concern. C++17 has http://eel.is/c++draft/dcl.attr.unused#2, but that may be too high of a bar

Comment (winkj) [reply SHTSensor.h]: should I just update this to ```SHTSensor::SHTAccuracy /* newAccuracy */```, which should fix the warning as well?

Comment (rnestler) [reply SHTSensor.h]: > I figured Arduino is mainly g++, but valid concern.

I'm not sure what compiler the ESP32 based Arduino's use, but AFAIK it's not gcc/g++.

> should I just update this to `SHTSensor::SHTAccuracy /* newAccuracy */`, which should fix the warning as well?

Would work, alternatively you can just do:
```cpp
   virtual bool setAccuracy(__attribute__((unused)) SHTSensor::SHTAccuracy newAccuracy) {
       (void)newAccuracy; // silence warning about unused argument
       return false;
   }
```

**Review by rnestler — APPROVED** [review]
